### PR TITLE
Adding a way for make visible Tag with different api-docs URL.

### PR DESCRIPTION
**Pull request by JFDionne**
Adding a way for make visible Tag with different api-docs URL.

A suggestion for #100 

By example:

> 	Routing.RouteTable.Routes.Add(new ServiceRoute("api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));
> 	Routing.RouteTable.Routes.Add(new ServiceRoute("api-docs2", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));
> 
> 	SwaggerWcfEndpoint.Add_VisibleTag("api-docs", "Service_1");
> 	SwaggerWcfEndpoint.Add_VisibleTag("api-docs2", "Service_2");

I'm not sure I'm doing it by the best way, but it's working.

Not sure about your standard of naming function and vars, hope it's fine.

### CODE REVIEW

**Comment by abelsilva** [comment]
why such a complex solution?

Can't you just work out with this?

```

            if (ConfigurationManager.AppSettings["api-docs_visible"] == "true")
                RouteTable.Routes.Add(new ServiceRoute("api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));
            if (ConfigurationManager.AppSettings["api-docs2_visible"] == "true")
                RouteTable.Routes.Add(new ServiceRoute("api-docs2", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));

```

```
  <appSettings>
    <add key="api-docs_visible" value="false"/>
    <add key="api-docs2_visible" value="true"/>
  </appSettings>
```

**Comment by abelsilva** [comment]
assuming you want to display/hide and endpoint...

**Comment by JFDionne** [comment]
no, the goal here is to display different tags depending of the endpoint of the docs. 

I put all my function/sub with SwaggerWcfHidden. And I make them visible depending of the url, by example, if I have service1.svc with function1 and function2, with service2.svc with function3 and function4, I can do something like http://URL/service1.svc/api-docs and it will put the swagguer only for function1 and function2.

if I do http://URL/service2.svc/api-docs that will show only function3 and 4

**Comment by abelsilva** [comment]
not using the PR you submitted, but I'm applying an update in a few moments that will support this with another approach, look into Global.asax.cs to check it after the updates

**Comment by JFDionne** [comment]
thank :) I'll check it

**Comment by JFDionne** [comment]
I tried, but maybe I don't understand something, when I do it the first time it seem to work, but if I go on my second api-docs it still show the tags of the first one.

`public void Application_Start(object sender, EventArgs e)
{
	SwaggerWcfEndpoint.FilterVisibleTags = FilterVisibleTags;
	SwaggerWcfEndpoint.FilterHiddenTags = FilterHiddenTags;
	SwaggerWcfEndpoint.DisableSwaggerUI = false;

	Routing.RouteTable.Routes.Add(new ServiceRoute("Service_Repartition/api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));
	Routing.RouteTable.Routes.Add(new ServiceRoute("Service_TA/api-docs", new WebServiceHostFactory(), typeof(SwaggerWcfEndpoint)));

	Routing.RouteTable.Routes.Add(new ServiceRoute("Service_Repartition/", new WebServiceHostFactory(), typeof(Webservice_Repartition.Service_TA_REST)));
	Routing.RouteTable.Routes.Add(new ServiceRoute("Service_TA/", new WebServiceHostFactory(), typeof(Webservice_Repartition.Service_TA_REST)));

	Routing.RouteTable.Routes.Add(new ServiceRoute("Webservice_Repartition/Service_Telephonique.svc", new WebServiceHostFactory(), typeof(Webservice_Repartition.Service_Telephonique)));


}

private static List<string> FilterVisibleTags(string[] path, List<string> visibleTags)
{

	if (path.Contains("/Service_Repartition/api-docs")) {
		visibleTags.Add("Service_REST");
		visibleTags.Add("Service_REST_Callback");
	}

	if (path.Contains("Service_TA/api-docs")) {
		visibleTags.Add("Service_TA_REST");
	}

	return visibleTags;
}`

**Comment by abelsilva** [comment]
You do not add tags, you remove them from the list

It’s a filter
-- 

---

Abel Silva

abel.silva@gmail.com

**Comment by JFDionne** [comment]
Okay, I just did the remove, but I got the same problem, I jsut did a debug and it seem function don't get called another time when I go on the second api-docs.

**Comment by abelsilva** [comment]
Ah... I see...

I think I know what the issue is, I’ll fix it later today

I’m preventing regenerating the swagger json multiple times
I’ll probably change the signature of the filters from string[] paths to
string path

-- 

---

Abel Silva

abel.silva@gmail.com

**Comment by JFDionne** [comment]
Okay, thank :)

**Comment by abelsilva** [comment]
check if latest version fixed this please

also, in the filter function you can add tags as you tried first (you are not limited to removing)

**Comment by JFDionne** [comment]
Seem to work, thank :)

But I think the global is not updated, it's still a list of string.

**Comment by abelsilva** [comment]
not sure what you meant

The functions are updated:

https://github.com/abelsilva/swaggerwcf/blob/46d6367c174e43e7298c181e735c175c430a6d9e/src/SwaggerWcf.Test.Service/Global.asax.cs#L32

https://github.com/abelsilva/swaggerwcf/blob/46d6367c174e43e7298c181e735c175c430a6d9e/src/SwaggerWcf.Test.Service/Global.asax.cs#L37

The change was for the `path` parameter, previously it was `string[] paths`, now it's `string path`

**Comment by JFDionne** [comment]
Forget it, I think I got the cache from my browser :)

**Pull request closed without merging**
