### PR TITLE
Security Integration and Bugfixes

### PR DESCRIPTION
**Pull request by SeeSharp7**
Hey Abel Silva, i love this swagger wcf project and I am using this via NuGet. As I missed some features/bugfixes, I made them in my free time. It would be nice, if you can merge them up :) 

Best regards from Germany
René

### CODE REVIEW

**Comment by abelsilva** [comment]
Hi René

Thanks for the support!

Can you review the Readme.md?

When I preview the changes I'm seeing many headers with wrong format and also, the table with formatting errors

Or maybe it's an issue with the previewer for PRs?

image

**Comment by SeeSharp7** [comment]
Hi Abel,
thank you for your response :)

I have this problem, too. I think, this is an issue with the previewer. In my studio (+ [this Markdown Editor](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor)) it looks fine: 
image

**Comment by abelsilva** [comment]
I think it's related to some spaces on the start of each line, you can view the final result on your branch
https://github.com/SeeSharp7/swaggerwcf/


image

**Comment by SeeSharp7** [comment]
Ah, you're right, thanks! I removed the leading spaces and now it looks great in preview :)

**Pull request merged**
