### PR TITLE
Update ISwaggerWcfEndpoint.cs

### PR DESCRIPTION
**Pull request by justin0522**
set the interface public

### CODE REVIEW

**Comment by abelsilva** [comment]
why?

**Comment by justin0522** [comment]
```
<services>
  <service name="SwaggerWcf.SwaggerWcfEndpoint">
    <endpoint address="http://localhost/docs" binding="webHttpBinding" contract="SwaggerWcf.ISwaggerWcfEndpoint" />
  </service>
</services>
```

when i add this endpoint with code, i can not access the interface

**Comment by abelsilva** [comment]
tks!
I don't use it as standalone, didn't notice that

**Comment by abelsilva** [comment]
https://www.nuget.org/packages/SwaggerWcf/0.2.15
should be online in a few minutes

**Pull request merged**
