### PR TITLE
Generate swagger file after build

### PR DESCRIPTION
**Pull request by pouladpld**
This would generate `swagger.json` after build and could be easily used in CI.

The generated file is not valid yet but it works. Please give me feedback so I enhance it.

In my organization, we take swagger files from multiple services and feed them into a unified documentation platform that understands Swagger2 as well. We don't use Swagger UI and there is no need to keep calling the swagger endpoint every single time the specs are needed.

### CODE REVIEW

**Comment by pouladpld** [comment]
To see the result, just build the solution amd open `swagger.json` in `Service.Test\bin` folder.

**Comment by pouladpld** [comment]
@abelsilva What do you think about this?

Another thing that I might add is attributes for the API info because if they are set in `Global.asax` file, I cannot take them using reflection. A few more attributes on `ServiceContract` would make it happen.

**Comment by abelsilva** [comment]
the project that you have on the CI env (that includes SwaggerWcf package) has a publish profile, right?

**Comment by pouladpld** [comment]
@abelsilva No. Does it matter?

**Comment by abelsilva** [comment]
I guess you might need to install iisexpress on the build server

**Comment by pouladpld** [comment]
Yes. We already talked about that and we decided best is to generate swagger file postbuild instead of telling every team who uses this package in organization to configure their CI and build server.

**Comment by abelsilva** [comment]
seems you are overcomplicating things
also, you are adding a lot of changes to this PR that are not related

why doesn't a simple powershell script work with the current version?

**Comment by pouladpld** [comment]
Give me some time to complete a few things.  Unfortunately, models and generators aren't easy to call statically.

You know framework the best. Make that PS script work and I'll cancel this PR :smile:

**Comment by abelsilva** [comment]
does this work like you want?

```
$ErrorActionPreference = "Stop"

$dllFiles = Get-ChildItem -Filter *.dll | ForEach-Object {$_.FullName}
$dllFiles | ForEach-Object {
    $__ = [Reflection.Assembly]::LoadFile($_)
}

$info = [SwaggerWcf.Models.Info]::new()
$info.Title = "CI"
$info.Description = "CI BUILD"
$info.Version = "9.9"

[SwaggerWcf.SwaggerWcfEndpoint]::Configure($info)
$swagger = [SwaggerWcf.SwaggerWcfEndpoint]::new()
$stream = $swagger.GetSwaggerFile()
$streamReader = [System.IO.StreamReader]::new($stream)
$jsonContents = $streamReader.ReadToEnd()
# Write-Host $jsonContents
$file = (Resolve-Path .\).Path + "\swagger.json"
[System.IO.File]::WriteAllText($file, $jsonContents)
```

**Comment by pouladpld** [comment]
@abelsilva ya. this works fine. :+1: 

Only thing I see is having `swagger.info` values as attributes so they could also be generated.

Do you have any plans to provide such script in the package?

**Comment by abelsilva** [comment]
attributes of? powershell script?

**Comment by abelsilva** [comment]
```
param (
    [string]$infoTitle = "CI", 
    [string]$infoDescription = "CI BUILD",    
    [string]$Version = "9.9",
)

$ErrorActionPreference = "Stop"

$dllFiles = Get-ChildItem -Filter *.dll | ForEach-Object {$_.FullName}
$dllFiles | ForEach-Object {
    $__ = [Reflection.Assembly]::LoadFile($_)
}

$info = [SwaggerWcf.Models.Info]::new()
$info.Title = $infoTitle
$info.Description = $infoDescription
$info.Version = $infoVersion

[SwaggerWcf.SwaggerWcfEndpoint]::Configure($info)
$swagger = [SwaggerWcf.SwaggerWcfEndpoint]::new()
$stream = $swagger.GetSwaggerFile()
$streamReader = [System.IO.StreamReader]::new($stream)
$jsonContents = $streamReader.ReadToEnd()
# Write-Host $jsonContents
$file = (Resolve-Path .\).Path + "\swagger.json"
[System.IO.File]::WriteAllText($file, $jsonContents)
```

**Comment by pouladpld** [comment]
@abelsilva 

> attributes of?

Service info could be in the form of attributes as well so it would be generated by reflection. [See here](https://github.com/pouladpld/swaggerwcf/blob/73716081b520c586a6e23574feb4bf2c908712dc/src/SwaggerWcf.Test.Service/IStore.cs#L13-L39)

Instantiating an info obj in PS script isn't a good idea as it's just duplicated settings.

>  powershell script?

Yes. A parameterized PS script in SwaggerWcf package. This allows whoever uses this package to just add the following to `.csproj` file and have the swagger file ready.

```xml
  <Target Name="AfterBuild">
    <Exec WorkingDirectory="bin" Command="powershell -File .\gen.ps1">
    </Exec>
  </Target>
```

**Comment by abelsilva** [comment]
> Service info could be in the form of attributes as well so it would be generated by reflection

make a PR only with these changes

> A parameterized PS script in SwaggerWcf package

doesn't make much sense to include your CI powershell script in the package for everyone else
you should keep your CI build scripts in your own environment

**Comment by pouladpld** [comment]
Will make the PR.

Script could be in the package as it is a way to generate the swagger file without run/deploy the web service. It isn't only for my CI env. Any one can add it to his project to have the file ready after build.

**Comment by pouladpld** [comment]
@abelsilva 

Side note: I know you started this project using an older version of `NewtonSoft.Json` package, but things there have improved a lot since then. There isn't any need to kinda manually serialize everything. All is needed is to use reflection to build an swagger schema object (Service class) and the pass it to `JsonConvert.Serialize()`. The changes I made for this PR are in that direction.

**Comment by abelsilva** [comment]
closing this since this PR has a lot more things in it that are not related

**Pull request closed without merging**
